sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tNVZ7iN1pPqnnne97wh
    access-key-secret: P8vnVJhH2gmRnm4sCFD7UtNMOxIgvq
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: slk-sky
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx29ddfa7264ca47d2
    secret: 2ce7a6393d7f264472ab440e1b871da6